# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-30 11:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('index_title1', models.CharField(max_length=100)),
                ('index_headings1', models.CharField(max_length=100)),
                ('index_description1', models.TextField()),
                ('index_title2', models.CharField(max_length=100)),
                ('index_headings2', models.CharField(max_length=100)),
                ('index_description2', models.TextField()),
                ('index_title3', models.CharField(max_length=100)),
                ('index_link3', models.TextField()),
                ('index_text', models.TextField()),
                ('index_title4', models.CharField(max_length=100)),
                ('index_link4', models.TextField()),
            ],
        ),
    ]
