# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-08-01 23:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datascience', '0005_feedback'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Emails',
        ),
    ]
