# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-08-01 23:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datascience', '0006_delete_emails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='message',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='subject',
        ),
    ]
