# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-08-01 23:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('datascience', '0007_auto_20180801_2351'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='date_subscribed',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
