# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-08-02 00:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datascience', '0008_feedback_date_subscribed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='date_subscribed',
        ),
    ]
